# Generated by Django 3.2.9 on 2021-12-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_build_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='user',
        ),
    ]
