# Generated by Django 3.2.9 on 2021-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_remove_build_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.CharField(default='a user', max_length=50),
        ),
    ]
