# Generated by Django 3.2.9 on 2021-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(default=None, max_length=1000)),
                ('component_type', models.CharField(choices=[('1', 'PROCESSOR'), ('2', 'MOTHERBOARD'), ('3', 'GRAPHICS CARD'), ('4', 'CASE'), ('5', 'MEMORY'), ('6', 'STORAGE')], max_length=300)),
                ('price', models.IntegerField()),
                ('place_to_buy', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
