# Generated by Django 3.2.9 on 2021-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('Processor', 'CPU'), ('Motherboard', 'MB'), ('Graphics Card', 'GPU'), ('Case', 'CASE'), ('Memory', 'RAM'), ('Storage', 'STO')], max_length=300),
        ),
    ]
