# Generated by Django 3.2.9 on 2021-12-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(choices=[('Processor', 'CPU'), ('Motherboard', 'MB'), ('Graphics Card', 'GPU'), ('Case', 'CASE'), ('Memory', 'RAM'), ('Storage', 'STO'), ('Power Supply', 'PSP')], max_length=300),
        ),
    ]
